[package]
name = "game-engine-0"
version = "0.1.0"
authors = ["Kumar Ayush <cheekujodhpur@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
